using ExpenseTracker.Domain.Entities;
using System.Linq;

namespace ExpenseTracker.Infrastructure.Persistence
{
    /// <summary>
    /// Reference data for the Merchants table: the 200 most common UK merchants, plus the
    /// alternative spellings receipts print for them.
    ///
    /// Normalized keys are computed with <see cref="Merchant.Normalize"/> rather than hand-typed,
    /// so the seed can never drift from the runtime lookup. Both collections feed EF's HasData,
    /// which requires stable ids — APPEND new rows at the end, never reorder or renumber existing
    /// ones, or the next migration will rewrite unrelated rows.
    /// </summary>
    public static class MerchantSeedData
    {
        private static object M(int id, string name, string website) =>
            new { Id = id, Name = name, NormalizedName = Merchant.Normalize(name), Website = (string?)website };

        public static readonly object[] Merchants =
        {
            // Grocery & supermarkets
            M(1,  "Tesco",              "tesco.com"),
            M(2,  "Sainsbury's",        "sainsburys.co.uk"),
            M(3,  "Asda",               "asda.com"),
            M(4,  "Morrisons",          "morrisons.com"),
            M(5,  "Aldi",               "aldi.co.uk"),
            M(6,  "Lidl",               "lidl.co.uk"),
            M(7,  "Co-op",              "coop.co.uk"),
            M(8,  "Waitrose",           "waitrose.com"),
            M(9,  "Marks & Spencer",    "marksandspencer.com"),
            M(10, "Iceland",            "iceland.co.uk"),
            M(11, "Ocado",              "ocado.com"),
            M(12, "Booths",             "booths.co.uk"),
            M(13, "Farmfoods",          "farmfoods.co.uk"),
            M(14, "Budgens",            "budgens.co.uk"),
            M(15, "Nisa",               "nisalocally.co.uk"),
            M(16, "Spar",               "spar.co.uk"),
            M(17, "Costcutter",         "costcutter.co.uk"),
            M(18, "Londis",             "londis.co.uk"),
            M(19, "Premier Stores",     "premier-stores.co.uk"),
            M(20, "Costco",             "costco.co.uk"),
            M(21, "Makro",              "makro.co.uk"),
            M(22, "Booker",             "booker.co.uk"),
            M(23, "Whole Foods Market", "wholefoodsmarket.co.uk"),
            M(24, "Holland & Barrett",  "hollandandbarrett.com"),
            M(25, "Gousto",             "gousto.co.uk"),

            // Fuel & motoring
            M(26, "Shell",              "shell.co.uk"),
            M(27, "BP",                 "bp.com"),
            M(28, "Esso",               "esso.co.uk"),
            M(29, "Texaco",             "texaco.co.uk"),
            M(30, "Gulf",               "gulfoil.co.uk"),
            M(31, "Jet",                "jetlocal.co.uk"),
            M(32, "Applegreen",         "applegreenstores.com"),
            M(33, "Murco",              "murcopetroleum.co.uk"),
            M(34, "Halfords",           "halfords.com"),
            M(35, "Kwik Fit",           "kwik-fit.com"),
            M(36, "ATS Euromaster",     "atseuromaster.co.uk"),
            M(37, "National Tyres",     "national.co.uk"),
            M(38, "Euro Car Parts",     "eurocarparts.com"),
            M(39, "RAC",                "rac.co.uk"),
            M(40, "AA",                 "theaa.com"),

            // Dining & coffee
            M(41, "Costa Coffee",       "costa.co.uk"),
            M(42, "Starbucks",          "starbucks.co.uk"),
            M(43, "Caffe Nero",         "caffenero.com"),
            M(44, "Pret A Manger",      "pret.co.uk"),
            M(45, "Greggs",             "greggs.co.uk"),
            M(46, "McDonald's",         "mcdonalds.com"),
            M(47, "Burger King",        "burgerking.co.uk"),
            M(48, "KFC",                "kfc.co.uk"),
            M(49, "Subway",             "subway.com"),
            M(50, "Nando's",            "nandos.co.uk"),
            M(51, "Wagamama",           "wagamama.com"),
            M(52, "Pizza Express",      "pizzaexpress.com"),
            M(53, "Domino's",           "dominos.co.uk"),
            M(54, "Pizza Hut",          "pizzahut.co.uk"),
            M(55, "Papa John's",        "papajohns.co.uk"),
            M(56, "Five Guys",          "fiveguys.co.uk"),
            M(57, "Wimpy",              "wimpy.uk.com"),
            M(58, "Leon",               "leon.co.uk"),
            M(59, "Itsu",               "itsu.com"),
            M(60, "Wasabi",             "wasabi.uk.com"),
            M(61, "YO! Sushi",          "yosushi.com"),
            M(62, "Bella Italia",       "bellaitalia.co.uk"),
            M(63, "Zizzi",              "zizzi.co.uk"),
            M(64, "Ask Italian",        "askitalian.co.uk"),
            M(65, "Prezzo",             "prezzorestaurants.co.uk"),
            M(66, "TGI Fridays",        "tgifridays.co.uk"),
            M(67, "Harvester",          "harvester.co.uk"),
            M(68, "Toby Carvery",       "tobycarvery.co.uk"),
            M(69, "Beefeater",          "beefeater.co.uk"),
            M(70, "Miller & Carter",    "millerandcarter.co.uk"),
            M(71, "Wetherspoon",        "jdwetherspoon.com"),
            M(72, "Slug and Lettuce",   "slugandlettuce.co.uk"),
            M(73, "Deliveroo",          "deliveroo.co.uk"),
            M(74, "Just Eat",           "just-eat.co.uk"),
            M(75, "Uber Eats",          "ubereats.com"),

            // Transport & travel
            M(76,  "Transport for London", "tfl.gov.uk"),
            M(77,  "Trainline",            "thetrainline.com"),
            M(78,  "National Rail",        "nationalrail.co.uk"),
            M(79,  "LNER",                 "lner.co.uk"),
            M(80,  "Avanti West Coast",    "avantiwestcoast.co.uk"),
            M(81,  "GWR",                  "gwr.com"),
            M(82,  "Southeastern",         "southeasternrailway.co.uk"),
            M(83,  "Northern",             "northernrailway.co.uk"),
            M(84,  "ScotRail",             "scotrail.co.uk"),
            M(85,  "CrossCountry",         "crosscountrytrains.co.uk"),
            M(86,  "Thameslink",           "thameslinkrailway.com"),
            M(87,  "Uber",                 "uber.com"),
            M(88,  "Bolt",                 "bolt.eu"),
            M(89,  "Addison Lee",          "addisonlee.com"),
            M(90,  "National Express",     "nationalexpress.com"),
            M(91,  "Megabus",              "megabus.com"),
            M(92,  "Stagecoach",           "stagecoachbus.com"),
            M(93,  "First Bus",            "firstbus.co.uk"),
            M(94,  "Arriva",               "arrivabus.co.uk"),
            M(95,  "easyJet",              "easyjet.com"),
            M(96,  "Ryanair",              "ryanair.com"),
            M(97,  "British Airways",      "britishairways.com"),
            M(98,  "Jet2",                 "jet2.com"),
            M(99,  "TUI",                  "tui.co.uk"),
            M(100, "Eurostar",             "eurostar.com"),

            // General retail
            M(101, "Amazon",           "amazon.co.uk"),
            M(102, "eBay",             "ebay.co.uk"),
            M(103, "Argos",            "argos.co.uk"),
            M(104, "John Lewis",       "johnlewis.com"),
            M(105, "Next",             "next.co.uk"),
            M(106, "Primark",          "primark.com"),
            M(107, "Debenhams",        "debenhams.com"),
            M(108, "House of Fraser",  "houseoffraser.co.uk"),
            M(109, "Selfridges",       "selfridges.com"),
            M(110, "Harrods",          "harrods.com"),
            M(111, "TK Maxx",          "tkmaxx.com"),
            M(112, "Sports Direct",    "sportsdirect.com"),
            M(113, "JD Sports",        "jdsports.co.uk"),
            M(114, "Decathlon",        "decathlon.co.uk"),
            M(115, "Nike",             "nike.com"),
            M(116, "Adidas",           "adidas.co.uk"),
            M(117, "Zara",             "zara.com"),
            M(118, "H&M",              "hm.com"),
            M(119, "Uniqlo",           "uniqlo.com"),
            M(120, "River Island",     "riverisland.com"),
            M(121, "New Look",         "newlook.com"),
            M(122, "ASOS",             "asos.com"),
            M(123, "Boohoo",           "boohoo.com"),
            M(124, "Shein",            "shein.co.uk"),
            M(125, "Currys",           "currys.co.uk"),
            M(126, "AO",               "ao.com"),
            M(127, "Apple",            "apple.com"),
            M(128, "Samsung",          "samsung.com"),
            M(129, "Game",             "game.co.uk"),
            M(130, "Smyths Toys",      "smythstoys.com"),

            // DIY, home & garden
            M(131, "B&Q",              "diy.com"),
            M(132, "Screwfix",         "screwfix.com"),
            M(133, "Wickes",           "wickes.co.uk"),
            M(134, "Homebase",         "homebase.co.uk"),
            M(135, "Toolstation",      "toolstation.com"),
            M(136, "Travis Perkins",   "travisperkins.co.uk"),
            M(137, "Jewson",           "jewson.co.uk"),
            M(138, "IKEA",             "ikea.com"),
            M(139, "Dunelm",           "dunelm.com"),
            M(140, "The Range",        "therange.co.uk"),
            M(141, "Wilko",            "wilko.com"),
            M(142, "Home Bargains",    "homebargains.co.uk"),
            M(143, "B&M",              "bmstores.co.uk"),
            M(144, "Poundland",        "poundland.co.uk"),
            M(145, "Poundstretcher",   "poundstretcher.co.uk"),
            M(146, "Robert Dyas",      "robertdyas.co.uk"),
            M(147, "Wayfair",          "wayfair.co.uk"),
            M(148, "Made",             "made.com"),
            M(149, "DFS",              "dfs.co.uk"),
            M(150, "Dobbies",          "dobbies.com"),

            // Pharmacy, health & beauty
            M(151, "Boots",            "boots.com"),
            M(152, "Superdrug",        "superdrug.com"),
            M(153, "Lloyds Pharmacy",  "lloydspharmacy.com"),
            M(154, "Well Pharmacy",    "well.co.uk"),
            M(155, "The Body Shop",    "thebodyshop.com"),
            M(156, "Lush",             "lush.com"),
            M(157, "Sephora",          "sephora.co.uk"),
            M(158, "Space NK",         "spacenk.com"),
            M(159, "Specsavers",       "specsavers.co.uk"),
            M(160, "Vision Express",   "visionexpress.com"),
            M(161, "Bupa",             "bupa.co.uk"),
            M(162, "Nuffield Health",  "nuffieldhealth.com"),
            M(163, "PureGym",          "puregym.com"),
            M(164, "The Gym Group",    "thegymgroup.com"),
            M(165, "David Lloyd",      "davidlloyd.co.uk"),

            // Telecom & utilities
            M(166, "BT",               "bt.com"),
            M(167, "EE",               "ee.co.uk"),
            M(168, "Vodafone",         "vodafone.co.uk"),
            M(169, "O2",               "o2.co.uk"),
            M(170, "Three",            "three.co.uk"),
            M(171, "Sky",              "sky.com"),
            M(172, "Virgin Media",     "virginmedia.com"),
            M(173, "TalkTalk",         "talktalk.co.uk"),
            M(174, "Plusnet",          "plus.net"),
            M(175, "Giffgaff",         "giffgaff.com"),
            M(176, "Tesco Mobile",     "tescomobile.com"),
            M(177, "British Gas",      "britishgas.co.uk"),
            M(178, "EDF Energy",       "edfenergy.com"),
            M(179, "E.ON",             "eonnext.com"),
            M(180, "Octopus Energy",   "octopus.energy"),
            M(181, "OVO Energy",       "ovoenergy.com"),
            M(182, "Scottish Power",   "scottishpower.co.uk"),
            M(183, "SSE",              "sse.co.uk"),
            M(184, "Thames Water",     "thameswater.co.uk"),
            M(185, "Severn Trent",     "stwater.co.uk"),

            // Subscriptions & digital
            M(186, "Netflix",              "netflix.com"),
            M(187, "Spotify",              "spotify.com"),
            M(188, "Disney+",              "disneyplus.com"),
            M(189, "Amazon Prime Video",   "primevideo.com"),
            M(190, "NOW",                  "nowtv.com"),
            M(191, "Apple Music",          "music.apple.com"),
            M(192, "YouTube",              "youtube.com"),
            M(193, "Audible",              "audible.co.uk"),
            M(194, "Adobe",                "adobe.com"),
            M(195, "Microsoft",            "microsoft.com"),
            M(196, "Google",               "google.com"),
            M(197, "Dropbox",              "dropbox.com"),
            M(198, "PayPal",               "paypal.com"),
            M(199, "Klarna",               "klarna.com"),
            M(200, "TV Licensing",         "tvlicensing.co.uk"),

            // ── Extended UK merchant list ───────────────────────────────────────
            // Ids start at 1001, not 201: the identity sequence keeps running from where the
            // first 200 left off, so ids just above 200 belong to merchants created at runtime
            // by users. Leaving that range clear means this seed can never collide with them.
            // Supermarkets & convenience
            M(1001, "Amazon Fresh",             "amazon.co.uk"),
            M(1002, "Bargain Booze",            "bargainbooze.co.uk"),
            M(1003, "Bestway",                  "bestwaywholesale.co.uk"),
            M(1004, "Central England Co-op",    "centralengland.coop"),
            M(1005, "Country Range",            "countryrange.co.uk"),
            M(1006, "East of England Co-op",    "eastofengland.coop"),
            M(1007, "Fultons Foods",            "fultonsfoods.co.uk"),
            M(1008, "Heron Foods",              "heronfoods.com"),
            M(1009, "HISBE",                    "hisbe.co.uk"),
            M(1010, "Jack's",                   "jacks.co.uk"),
            M(1011, "Keystore",                 "keystoreconvenience.co.uk"),
            M(1012, "McColl's",                 "mccolls.co.uk"),
            M(1013, "Midcounties Co-operative", "midcounties.coop"),
            M(1014, "One Stop",                 "onestop.co.uk"),
            M(1015, "Parfetts",                 "parfetts.co.uk"),
            M(1016, "Poundbakery",              "poundbakery.co.uk"),
            M(1017, "Riverford",                "riverford.co.uk"),
            M(1018, "Scotmid",                  "scotmid.coop"),
            M(1019, "Simply Fresh",             "simplyfresh.co.uk"),
            M(1020, "Sunday Market",            "sundaymarket.co.uk"),
            M(1021, "The Food Warehouse",       "thefoodwarehouse.com"),
            M(1022, "Today's Local",            "todays.co.uk"),
            M(1023, "Abel & Cole",              "abelandcole.co.uk"),
            M(1024, "Approved Food",            "approvedfood.co.uk"),
            M(1025, "HelloFresh",               "hellofresh.co.uk"),
            M(1026, "Mindful Chef",             "mindfulchef.com"),
            M(1027, "Muscle Food",              "musclefood.com"),
            M(1028, "Oddbox",                   "oddbox.co.uk"),

            // Petrol & motoring
            M(1029, "BP Pulse",                "bppulse.co.uk"),
            M(1030, "Certas Energy",           "certasenergy.co.uk"),
            M(1031, "Harvest Energy",          "harvestenergy.co.uk"),
            M(1032, "Instavolt",               "instavolt.co.uk"),
            M(1033, "Ionity",                  "ionity.eu"),
            M(1034, "Motor Fuel Group",        "motorfuelgroup.com"),
            M(1035, "Osprey Charging",         "ospreycharging.co.uk"),
            M(1036, "Pod Point",               "pod-point.com"),
            M(1037, "Tesla Supercharger",      "tesla.com"),
            M(1038, "Arnold Clark",            "arnoldclark.com"),
            M(1039, "Autoglass",               "autoglass.co.uk"),
            M(1040, "Bristol Street Motors",   "bristolstreet.co.uk"),
            M(1041, "Car Shop",                "carshop.co.uk"),
            M(1042, "Cazoo",                   "cazoo.co.uk"),
            M(1043, "Cinch",                   "cinch.co.uk"),
            M(1044, "Evans Halshaw",           "evanshalshaw.com"),
            M(1045, "Formula One Autocentres", "f1autocentres.co.uk"),
            M(1046, "GSF Car Parts",           "gsfcarparts.com"),
            M(1047, "Hendy Group",             "hendy.co.uk"),
            M(1048, "Jardine Motors",          "jardinemotors.co.uk"),
            M(1049, "Lookers",                 "lookers.co.uk"),
            M(1050, "Marshall Motor Group",    "marshall.co.uk"),
            M(1051, "Micheldever Tyres",       "michelde.co.uk"),
            M(1052, "Motorpoint",              "motorpoint.co.uk"),
            M(1053, "Mr Clutch",               "mrclutch.com"),
            M(1054, "National Windscreens",    "nationalwindscreens.co.uk"),
            M(1055, "Pendragon",               "pendragonplc.com"),
            M(1056, "Protyre",                 "protyre.co.uk"),
            M(1057, "Sytner",                  "sytner.co.uk"),
            M(1058, "Tyre Shopper",            "tyreshopper.co.uk"),
            M(1059, "Vertu Motors",            "vertumotors.com"),
            M(1060, "Webuyanycar",             "webuyanycar.com"),
            M(1061, "Green Flag",              "greenflag.com"),
            M(1062, "Britannia Rescue",        "britanniarescue.com"),
            M(1063, "Start Rescue",            "startrescue.co.uk"),
            M(1064, "DVLA",                    "gov.uk"),
            M(1065, "Dart Charge",             "gov.uk"),
            M(1066, "M6 Toll",                 "m6toll.co.uk"),

            // Clothing & footwear
            M(1067, "Abercrombie & Fitch", "abercrombie.com"),
            M(1068, "Alexander McQueen",   "alexandermcqueen.com"),
            M(1069, "All Saints",          "allsaints.com"),
            M(1070, "Ann Summers",         "annsummers.com"),
            M(1071, "Aquascutum",          "aquascutum.com"),
            M(1072, "Arket",               "arket.com"),
            M(1073, "Barbour",             "barbour.com"),
            M(1074, "Bershka",             "bershka.com"),
            M(1075, "Berghaus",            "berghaus.com"),
            M(1076, "Blacks",              "blacks.co.uk"),
            M(1077, "Boden",               "boden.co.uk"),
            M(1078, "Bonmarche",           "bonmarche.co.uk"),
            M(1079, "Burberry",            "burberry.com"),
            M(1080, "Burton",              "burton.co.uk"),
            M(1081, "Calvin Klein",        "calvinklein.co.uk"),
            M(1082, "Charles Tyrwhitt",    "charlestyrwhitt.com"),
            M(1083, "Clarks",              "clarks.co.uk"),
            M(1084, "Coast",               "coastfashion.com"),
            M(1085, "Cos",                 "cos.com"),
            M(1086, "Cotswold Outdoor",    "cotswoldoutdoor.com"),
            M(1087, "Crew Clothing",       "crewclothing.co.uk"),
            M(1088, "Deichmann",           "deichmann.com"),
            M(1089, "Dorothy Perkins",     "dorothyperkins.com"),
            M(1090, "Dr Martens",          "drmartens.com"),
            M(1091, "Dune London",         "dunelondon.com"),
            M(1092, "Ede & Ravenscroft",   "edeandravenscroft.com"),
            M(1093, "Fat Face",            "fatface.com"),
            M(1094, "Foot Asylum",         "footasylum.com"),
            M(1095, "Foot Locker",         "footlocker.co.uk"),
            M(1096, "French Connection",   "frenchconnection.com"),
            M(1097, "Gap",                 "gap.co.uk"),
            M(1098, "Gant",                "gant.co.uk"),
            M(1099, "George at Asda",      "asda.com"),
            M(1100, "Gymshark",            "gymshark.com"),
            M(1101, "Hackett",             "hackett.com"),
            M(1102, "Harvey Nichols",      "harveynichols.com"),
            M(1103, "Hobbs",               "hobbs.com"),
            M(1104, "Hollister",           "hollisterco.com"),
            M(1105, "Hotter Shoes",        "hotter.com"),
            M(1106, "House of CB",         "houseofcb.com"),
            M(1107, "Hugo Boss",           "hugoboss.com"),
            M(1108, "Jack Wills",          "jackwills.com"),
            M(1109, "Jaeger",              "jaeger.co.uk"),
            M(1110, "Jigsaw",              "jigsaw-online.com"),
            M(1111, "Joules",              "joules.com"),
            M(1112, "Karen Millen",        "karenmillen.com"),
            M(1113, "Kurt Geiger",         "kurtgeiger.com"),
            M(1114, "Lacoste",             "lacoste.com"),
            M(1115, "Levi's",              "levi.com"),
            M(1116, "Lipsy",               "lipsy.co.uk"),
            M(1117, "Long Tall Sally",     "longtallsally.com"),
            M(1118, "Lululemon",           "lululemon.co.uk"),
            M(1119, "Mango",               "shop.mango.com"),
            M(1120, "Mint Velvet",         "mintvelvet.com"),
            M(1121, "Missguided",          "missguided.co.uk"),
            M(1122, "Moss Bros",           "moss.co.uk"),
            M(1123, "Mountain Warehouse",  "mountainwarehouse.com"),
            M(1124, "Nobody's Child",      "nobodyschild.com"),
            M(1125, "Oasis",               "oasis-stores.com"),
            M(1126, "Office",              "office.co.uk"),
            M(1127, "Oliver Bonas",        "oliverbonas.com"),
            M(1128, "Paul Smith",          "paulsmith.com"),
            M(1129, "Pavers",              "pavers.co.uk"),
            M(1130, "Peacocks",            "peacocks.co.uk"),
            M(1131, "Phase Eight",         "phase-eight.com"),
            M(1132, "Pull & Bear",         "pullandbear.com"),
            M(1133, "Quiz Clothing",       "quizclothing.co.uk"),
            M(1134, "Rab",                 "rab.equipment"),
            M(1135, "Radley",              "radley.co.uk"),
            M(1136, "Ralph Lauren",        "ralphlauren.co.uk"),
            M(1137, "Reiss",               "reiss.com"),
            M(1138, "Regatta",             "regatta.com"),
            M(1139, "Rohan",               "rohan.co.uk"),
            M(1140, "Roman Originals",     "romanoriginals.co.uk"),
            M(1141, "Sports Shoes",        "sportsshoes.com"),
            M(1142, "Schuh",               "schuh.co.uk"),
            M(1143, "Seasalt Cornwall",    "seasaltcornwall.com"),
            M(1144, "Shoe Zone",           "shoezone.com"),
            M(1145, "Simply Be",           "simplybe.co.uk"),
            M(1146, "Size?",               "size.co.uk"),
            M(1147, "Skechers",            "skechers.co.uk"),
            M(1148, "Stradivarius",        "stradivarius.com"),
            M(1149, "Superdry",            "superdry.com"),
            M(1150, "Ted Baker",           "tedbaker.com"),
            M(1151, "The North Face",      "thenorthface.co.uk"),
            M(1152, "The Outnet",          "theoutnet.com"),
            M(1153, "Timberland",          "timberland.co.uk"),
            M(1154, "Toast",               "toa.st"),
            M(1155, "Tommy Hilfiger",      "uk.tommy.com"),
            M(1156, "Topshop",             "topshop.com"),
            M(1157, "Trespass",            "trespass.com"),
            M(1158, "Tu Clothing",         "sainsburys.co.uk"),
            M(1159, "Under Armour",        "underarmour.co.uk"),
            M(1160, "Urban Outfitters",    "urbanoutfitters.com"),
            M(1161, "Vans",                "vans.co.uk"),
            M(1162, "Very",                "very.co.uk"),
            M(1163, "Vivienne Westwood",   "viviennewestwood.com"),
            M(1164, "Warehouse",           "warehousefashion.com"),
            M(1165, "Weird Fish",          "weirdfish.co.uk"),
            M(1166, "White Company",       "thewhitecompany.com"),
            M(1167, "White Stuff",         "whitestuff.com"),
            M(1168, "Whistles",            "whistles.com"),
            M(1169, "Wallis",              "wallis.co.uk"),
            M(1170, "Yours Clothing",      "yoursclothing.co.uk"),
            M(1171, "Zalando",             "zalando.co.uk"),
            M(1172, "Jules B",             "julesb.co.uk"),
            M(1173, "End Clothing",        "endclothing.com"),
            M(1174, "Flannels",            "flannels.com"),
            M(1175, "Matches Fashion",     "matchesfashion.com"),
            M(1176, "Net a Porter",        "net-a-porter.com"),
            M(1177, "Represent",           "representclo.com"),

            // Restaurants, cafes & takeaways
            M(1178, "Bakers Plus",            "bakersplus.co.uk"),
            M(1179, "Banana Tree",            "bananatree.co.uk"),
            M(1180, "Barburrito",             "barburrito.co.uk"),
            M(1181, "Bill's",                 "bills-website.co.uk"),
            M(1182, "Bird",                   "birdrestaurants.com"),
            M(1183, "Black Sheep Coffee",     "leavetheherd.com"),
            M(1184, "Boston Tea Party",       "bostonteaparty.co.uk"),
            M(1185, "Boojum",                 "boojummex.com"),
            M(1186, "Browns Brasserie",       "browns-restaurants.co.uk"),
            M(1187, "Bubbleology",            "bubbleology.com"),
            M(1188, "Busaba",                 "busaba.com"),
            M(1189, "Cafe Rouge",             "caferouge.com"),
            M(1190, "Carluccio's",            "carluccios.com"),
            M(1191, "Chaiiwala",              "chaiiwala.co.uk"),
            M(1192, "Chai Point",             "chaipoint.co.uk"),
            M(1193, "Chiquito",               "chiquito.co.uk"),
            M(1194, "Chopstix",               "chopstixgroup.com"),
            M(1195, "Chozen Noodle",          "chozennoodle.com"),
            M(1196, "Ciao Bella",             "ciaobellarestaurant.co.uk"),
            M(1197, "Cafe Concerto",          "cafeconcerto.co"),
            M(1198, "Coco di Mama",           "cocodimama.co.uk"),
            M(1199, "Comptoir Libanais",      "comptoirlibanais.com"),
            M(1200, "Cote Brasserie",         "cote.co.uk"),
            M(1201, "Crussh",                 "crussh.com"),
            M(1202, "Das Sushi",              "dassushi.co.uk"),
            M(1203, "Dishoom",                "dishoom.com"),
            M(1204, "Ed's Easy Diner",        "edseasydiner.com"),
            M(1205, "Eat Tokyo",              "eattokyo.co.uk"),
            M(1206, "Franco Manca",           "francomanca.co.uk"),
            M(1207, "Frankie & Benny's",      "frankieandbennys.com"),
            M(1208, "Gail's Bakery",          "gailsbread.co.uk"),
            M(1209, "German Doner Kebab",     "germandonerkebab.com"),
            M(1210, "Giggling Squid",         "gigglingsquid.com"),
            M(1211, "Gourmet Burger Kitchen", "gbk.co.uk"),
            M(1212, "Greenwich Market",       "greenwichmarket.london"),
            M(1213, "Hard Rock Cafe",         "hardrockcafe.com"),
            M(1214, "Hawksmoor",              "thehawksmoor.com"),
            M(1215, "Honest Burgers",         "honestburgers.co.uk"),
            M(1216, "Ilford Kebab",           "ilfordkebab.co.uk"),
            M(1217, "Ippudo",                 "ippudo.co.uk"),
            M(1218, "Joe & The Juice",        "joejuice.com"),
            M(1219, "Kaspa's Desserts",       "kaspas.co.uk"),
            M(1220, "Krispy Kreme",           "krispykreme.co.uk"),
            M(1221, "La Tasca",               "latasca.com"),
            M(1222, "Las Iguanas",            "iguanas.co.uk"),
            M(1223, "Loungers",               "thelounges.co.uk"),
            M(1224, "Mowgli",                 "mowglistreetfood.com"),
            M(1225, "Nudo Sushi",             "nudosushibox.co.uk"),
            M(1226, "Ole & Steen",            "oleandsteen.co.uk"),
            M(1227, "Pasta Evangelists",      "pastaevangelists.com"),
            M(1228, "Patisserie Valerie",     "patisserie-valerie.co.uk"),
            M(1229, "Paul Bakery",            "paul-uk.com"),
            M(1230, "Pepe's Piri Piri",       "pepes.co.uk"),
            M(1231, "Pho",                    "phocafe.co.uk"),
            M(1232, "Pizza Pilgrims",         "pizzapilgrims.co.uk"),
            M(1233, "Pizza Punks",            "pizzapunks.co.uk"),
            M(1234, "Popeyes",                "popeyes.co.uk"),
            M(1235, "Rosa's Thai",            "rosasthai.com"),
            M(1236, "Roti King",              "rotiking.com"),
            M(1237, "Sakura",                 "sakurarestaurant.co.uk"),
            M(1238, "Shake Shack",            "shakeshack.co.uk"),
            M(1239, "Slim Chickens",          "slimchickens.co.uk"),
            M(1240, "Soho Coffee",            "sohocoffee.co.uk"),
            M(1241, "Sushi Daily",            "sushidaily.com"),
            M(1242, "Taco Bell",              "tacobell.co.uk"),
            M(1243, "Tortilla",               "tortilla.co.uk"),
            M(1244, "Turtle Bay",             "turtlebay.co.uk"),
            M(1245, "Wahaca",                 "wahaca.co.uk"),
            M(1246, "Wendy's",                "wendys.co.uk"),
            M(1247, "Wingstop",               "wingstop.co.uk"),
            M(1248, "Zambrero",               "zambrero.co.uk"),
            M(1249, "Bella Vista",            "bellavista.co.uk"),
            M(1250, "Big Mamma",              "bigmammagroup.com"),
            M(1251, "Bunsik",                 "bunsik.co.uk"),
            M(1252, "Chick King",             "chickking.co.uk"),
            M(1253, "Chicken Cottage",        "chickencottage.com"),
            M(1254, "Chicken Shop",           "chickenshop.com"),
            M(1255, "Dixy Chicken",           "dixychicken.co.uk"),
            M(1256, "Fish and Chips Co",      "fishandchips.co.uk"),
            M(1257, "Harry Ramsden's",        "harryramsdens.co.uk"),
            M(1258, "Morley's",               "morleys.co.uk"),
            M(1259, "Perfect Fried Chicken",  "pfcuk.co.uk"),
            M(1260, "Sam's Chicken",          "samschicken.co.uk"),
            M(1261, "Tossed",                 "tossed.com"),
            M(1262, "Vital Ingredient",       "vitalingredient.co.uk"),
            M(1263, "Abokado",                "abokado.com"),
            M(1264, "Benugo",                 "benugo.com"),
            M(1265, "Caffe Concerto",         "caffeconcerto.co.uk"),
            M(1266, "Coffee Republic",        "coffeerepublic.co.uk"),
            M(1267, "Department of Coffee",   "departmentofcoffee.com"),
            M(1268, "Grind",                  "grind.co.uk"),
            M(1269, "Harris and Hoole",       "harrisandhoole.co.uk"),
            M(1270, "Notes Coffee",           "notescoffee.com"),
            M(1271, "Puccino's",              "puccinos.com"),
            M(1272, "Taylor St Baristas",     "taylorstbaristas.com"),
            M(1273, "Tim Hortons",            "timhortons.co.uk"),
            M(1274, "Bageriet",               "bageriet.co.uk"),
            M(1275, "Bread Ahead",            "breadahead.com"),
            M(1276, "Cinnabon",               "cinnabon.co.uk"),
            M(1277, "Cookies and Cream",      "cookiesandcream.co.uk"),
            M(1278, "Crosstown Doughnuts",    "crosstown.co.uk"),
            M(1279, "Doughnut Time",          "doughnuttime.co.uk"),
            M(1280, "Dum Dums Donutterie",    "dumdumsdonutterie.co.uk"),
            M(1281, "Millie's Cookies",       "milliescookies.com"),
            M(1282, "Ben's Cookies",          "benscookies.com"),
            M(1283, "Creams Cafe",            "creamscafe.com"),
            M(1284, "Heavenly Desserts",      "heavenlydesserts.co.uk"),
            M(1285, "Shakeaway",              "shakeaway.com"),
            M(1286, "Snowflake Gelato",       "snowflakegelato.co.uk"),

            // Pubs & bars
            M(1287, "All Bar One",          "allbarone.co.uk"),
            M(1288, "Be At One",            "beatone.co.uk"),
            M(1289, "Brewdog",              "brewdog.com"),
            M(1290, "Brewers Fayre",        "brewersfayre.co.uk"),
            M(1291, "Chef & Brewer",        "chefandbrewer.com"),
            M(1292, "Craft Union",          "craftunionpubs.com"),
            M(1293, "Ember Inns",           "emberinns.co.uk"),
            M(1294, "Fayre & Square",       "fayre-square.com"),
            M(1295, "Fullers",              "fullers.co.uk"),
            M(1296, "Greene King",          "greeneking.co.uk"),
            M(1297, "Hungry Horse",         "hungryhorse.co.uk"),
            M(1298, "Innkeeper's Lodge",    "innkeeperscollection.co.uk"),
            M(1299, "Marstons",             "marstons.co.uk"),
            M(1300, "Mitchells & Butlers",  "mbplc.com"),
            M(1301, "Nicholson's Pubs",     "nicholsonspubs.co.uk"),
            M(1302, "O'Neill's",            "oneills.co.uk"),
            M(1303, "Premium Country Pubs", "premiumcountrypubs.co.uk"),
            M(1304, "Revolution Bars",      "revolutionbars.co.uk"),
            M(1305, "Sizzling Pubs",        "sizzlingpubs.co.uk"),
            M(1306, "Stonegate",            "stonegategroup.co.uk"),
            M(1307, "Stonehouse Pizza",     "stonehousepizzaandcarvery.co.uk"),
            M(1308, "Taylor Walker",        "taylor-walker.co.uk"),
            M(1309, "The Alchemist",        "thealchemist.uk.com"),
            M(1310, "Turtle Bay Bar",       "turtlebay.co.uk"),
            M(1311, "Vintage Inns",         "vintageinn.co.uk"),
            M(1312, "Wetherspoon Hotels",   "jdwetherspoon.com"),
            M(1313, "Young's",              "youngs.co.uk"),
            M(1314, "Simmons Bar",          "simmonsbar.co.uk"),
            M(1315, "Dirty Martini",        "dirtymartini.uk.com"),
            M(1316, "Flight Club",          "flightclubdarts.com"),
            M(1317, "Bounce",               "bouncepingpong.com"),
            M(1318, "Roxy Ball Room",       "roxyballroom.co.uk"),
            M(1319, "Tank & Paddle",        "tankandpaddle.co.uk"),
            M(1320, "Brewhouse & Kitchen",  "brewhouseandkitchen.com"),
            M(1321, "Craft Beer Co",        "thecraftbeerco.com"),

            // Health, pharmacy & opticians
            M(1322, "Asda Pharmacy",           "asda.com"),
            M(1323, "Boots Opticians",         "boots.com"),
            M(1324, "Cohens Chemist",          "cohenschemist.co.uk"),
            M(1325, "Day Lewis Pharmacy",      "daylewis.co.uk"),
            M(1326, "Rowlands Pharmacy",       "rowlandspharmacy.co.uk"),
            M(1327, "Superdrug Pharmacy",      "superdrug.com"),
            M(1328, "Tesco Pharmacy",          "tesco.com"),
            M(1329, "Pharmacy2U",              "pharmacy2u.co.uk"),
            M(1330, "Chemist 4 U",             "chemist-4-u.com"),
            M(1331, "Chemist Direct",          "chemistdirect.co.uk"),
            M(1332, "Echo Pharmacy",           "echo.co.uk"),
            M(1333, "Lloyds Direct",           "lloydsdirect.co.uk"),
            M(1334, "Weldricks",               "weldricks.co.uk"),
            M(1335, "Boots Hearingcare",       "boots.com"),
            M(1336, "Hidden Hearing",          "hiddenhearing.co.uk"),
            M(1337, "Amplifon",                "amplifon.com"),
            M(1338, "Scrivens",                "scrivens.com"),
            M(1339, "Optical Express",         "opticalexpress.co.uk"),
            M(1340, "Leightons Opticians",     "leightons.co.uk"),
            M(1341, "Asda Opticians",          "asda.com"),
            M(1342, "Tesco Opticians",         "tesco.com"),
            M(1343, "Glasses Direct",          "glassesdirect.co.uk"),
            M(1344, "Lenstore",                "lenstore.co.uk"),
            M(1345, "Feel Good Contacts",      "feelgoodcontacts.com"),
            M(1346, "Bupa Dental",             "bupa.co.uk"),
            M(1347, "Mydentist",               "mydentist.co.uk"),
            M(1348, "Portman Dental",          "portmandentalcare.com"),
            M(1349, "Rodericks Dental",        "rodericksdental.co.uk"),
            M(1350, "Smile Direct Club",       "smiledirectclub.co.uk"),
            M(1351, "Spire Healthcare",        "spirehealthcare.com"),
            M(1352, "Circle Health",           "circlehealthgroup.co.uk"),
            M(1353, "Ramsay Health Care",      "ramsayhealth.co.uk"),
            M(1354, "Nuffield Hospital",       "nuffieldhealth.com"),
            M(1355, "Babylon Health",          "babylonhealth.com"),
            M(1356, "Push Doctor",             "pushdoctor.co.uk"),
            M(1357, "Livi",                    "livi.co.uk"),
            M(1358, "Zava",                    "zavamed.com"),
            M(1359, "Superdrug Online Doctor", "onlinedoctor.superdrug.com"),
            M(1360, "NHS Prescription",        "nhs.uk"),
            M(1361, "Randox Health",           "randoxhealth.com"),

            // Beauty & cosmetics
            M(1362, "Aveda",                "aveda.co.uk"),
            M(1363, "Beauty Bay",           "beautybay.com"),
            M(1364, "Beauty Pie",           "beautypie.com"),
            M(1365, "Benefit Cosmetics",    "benefitcosmetics.com"),
            M(1366, "Bobbi Brown",          "bobbibrown.co.uk"),
            M(1367, "Charlotte Tilbury",    "charlottetilbury.com"),
            M(1368, "Clarins",              "clarins.co.uk"),
            M(1369, "Clinique",             "clinique.co.uk"),
            M(1370, "Cult Beauty",          "cultbeauty.co.uk"),
            M(1371, "Elemis",               "elemis.com"),
            M(1372, "Estee Lauder",         "esteelauder.co.uk"),
            M(1373, "Feelunique",           "feelunique.com"),
            M(1374, "Glossier",             "glossier.com"),
            M(1375, "Kiehl's",              "kiehls.co.uk"),
            M(1376, "L'Occitane",           "loccitane.com"),
            M(1377, "Look Fantastic",       "lookfantastic.com"),
            M(1378, "MAC Cosmetics",        "maccosmetics.co.uk"),
            M(1379, "Molton Brown",         "moltonbrown.co.uk"),
            M(1380, "Neal's Yard Remedies", "nealsyardremedies.com"),
            M(1381, "Origins",              "origins.co.uk"),
            M(1382, "Rituals",              "rituals.com"),
            M(1383, "Sanctuary Spa",        "sanctuary.com"),
            M(1384, "Sculpted by Aimee",    "sculptedbyaimee.com"),
            M(1385, "Skinstore",            "skinstore.com"),
            M(1386, "The Ordinary",         "theordinary.com"),
            M(1387, "The Perfume Shop",     "theperfumeshop.com"),
            M(1388, "Toni & Guy",           "toniandguy.com"),
            M(1389, "Jo Malone",            "jomalone.co.uk"),
            M(1390, "Penhaligon's",         "penhaligons.com"),
            M(1391, "Bleach London",        "bleachlondon.com"),
            M(1392, "Regis Salon",          "regissalons.co.uk"),
            M(1393, "Supercuts",            "supercuts.co.uk"),
            M(1394, "Nails Inc",            "nailsinc.com"),
            M(1395, "Sweaty Betty Beauty",  "sweatybetty.com"),
            M(1396, "Fragrance Direct",     "fragrancedirect.co.uk"),

            // Electronics & tech
            M(1397, "Argos Tech",        "argos.co.uk"),
            M(1398, "BT Shop",           "btshop.bt.com"),
            M(1399, "CeX",               "webuy.com"),
            M(1400, "Cash Converters",   "cashconverters.co.uk"),
            M(1401, "Dell",              "dell.co.uk"),
            M(1402, "Ebuyer",            "ebuyer.com"),
            M(1403, "Elekdirect",        "elekdirect.co.uk"),
            M(1404, "Google Store",      "store.google.com"),
            M(1405, "HP Store",          "hp.com"),
            M(1406, "Hughes",            "hughes.co.uk"),
            M(1407, "Insight UK",        "uk.insight.com"),
            M(1408, "John Lewis Tech",   "johnlewis.com"),
            M(1409, "Laptops Direct",    "laptopsdirect.co.uk"),
            M(1410, "Lenovo",            "lenovo.com"),
            M(1411, "Maplin",            "maplin.co.uk"),
            M(1412, "Marks Electrical",  "markselectrical.co.uk"),
            M(1413, "Novatech",          "novatech.co.uk"),
            M(1414, "Overclockers UK",   "overclockers.co.uk"),
            M(1415, "PC Specialist",     "pcspecialist.co.uk"),
            M(1416, "Richer Sounds",     "richersounds.com"),
            M(1417, "Scan Computers",    "scan.co.uk"),
            M(1418, "Sonos",             "sonos.com"),
            M(1419, "Sony",              "sony.co.uk"),
            M(1420, "Very Tech",         "very.co.uk"),
            M(1421, "Box",               "box.co.uk"),
            M(1422, "Amazon Devices",    "amazon.co.uk"),
            M(1423, "Bose",              "bose.co.uk"),
            M(1424, "Dyson",             "dyson.co.uk"),
            M(1425, "GAME Digital",      "game.co.uk"),
            M(1426, "Nintendo Store",    "nintendo.co.uk"),
            M(1427, "PlayStation Store", "playstation.com"),
            M(1428, "Xbox Store",        "xbox.com"),
            M(1429, "Steam",             "steampowered.com"),
            M(1430, "Epic Games",        "epicgames.com"),
            M(1431, "Music Magpie",      "musicmagpie.co.uk"),

            // Home, furniture & DIY
            M(1432, "Anglian Home",              "anglianhome.co.uk"),
            M(1433, "Bensons for Beds",          "bensonsforbeds.co.uk"),
            M(1434, "Bathstore",                 "bathstore.com"),
            M(1435, "Bathroom Village",          "bathroomvillage.com"),
            M(1436, "Betta Living",              "bettaliving.co.uk"),
            M(1437, "Buildbase",                 "buildbase.co.uk"),
            M(1438, "Carpetright",               "carpetright.co.uk"),
            M(1439, "City Plumbing",             "cityplumbing.co.uk"),
            M(1440, "Cotswold Company",          "cotswoldco.com"),
            M(1441, "Cox & Cox",                 "coxandcox.co.uk"),
            M(1442, "Dreams",                    "dreams.co.uk"),
            M(1443, "Dulux Decorator Centre",    "duluxdecoratorcentre.co.uk"),
            M(1444, "Fired Earth",               "firedearth.com"),
            M(1445, "Furniture Village",         "furniturevillage.co.uk"),
            M(1446, "Graham Plumbers Merchant",  "grahamplumbersmerchant.co.uk"),
            M(1447, "Habitat",                   "habitat.co.uk"),
            M(1448, "Harveys Furniture",         "harveysfurniture.co.uk"),
            M(1449, "Homesense",                 "homesense.com"),
            M(1450, "Howdens",                   "howdens.com"),
            M(1451, "Hillarys",                  "hillarys.co.uk"),
            M(1452, "Julian Charles",            "juliancharles.co.uk"),
            M(1453, "Laura Ashley",              "lauraashley.com"),
            M(1454, "Loaf",                      "loaf.com"),
            M(1455, "Magnet",                    "magnet.co.uk"),
            M(1456, "Maisons du Monde",          "maisonsdumonde.com"),
            M(1457, "MFI",                       "mfi.co.uk"),
            M(1458, "Neptune",                   "neptune.com"),
            M(1459, "Next Home",                 "next.co.uk"),
            M(1460, "Oak Furnitureland",         "oakfurnitureland.co.uk"),
            M(1461, "Plumbworld",                "plumbworld.co.uk"),
            M(1462, "Selco",                     "selcobw.com"),
            M(1463, "ScS",                       "scs.co.uk"),
            M(1464, "Sharps Bedrooms",           "sharps.co.uk"),
            M(1465, "Sofology",                  "sofology.co.uk"),
            M(1466, "Soak",                      "soak.com"),
            M(1467, "Swoon",                     "swooneditions.com"),
            M(1468, "Tile Giant",                "tilegiant.co.uk"),
            M(1469, "Tile Mountain",             "tilemountain.co.uk"),
            M(1470, "Topps Tiles",               "toppstiles.co.uk"),
            M(1471, "Victoria Plum",             "victoriaplum.com"),
            M(1472, "Wren Kitchens",             "wrenkitchens.com"),
            M(1473, "Brewers Decorator",         "brewers.co.uk"),
            M(1474, "Crown Paints",              "crownpaints.co.uk"),
            M(1475, "Farrow & Ball",             "farrow-ball.com"),
            M(1476, "Leyland SDM",               "leylandsdm.co.uk"),
            M(1477, "Machine Mart",              "machinemart.co.uk"),
            M(1478, "Axminster Tools",           "axminstertools.com"),
            M(1479, "ITS",                       "its.co.uk"),
            M(1480, "Ironmongery Direct",        "ironmongerydirect.co.uk"),
            M(1481, "Trade Point",               "trade-point.co.uk"),
            M(1482, "The Original Factory Shop", "tofs.com"),
            M(1483, "Matalan",                   "matalan.co.uk"),
            M(1484, "QD Stores",                 "qdstores.co.uk"),
            M(1485, "Boyes",                     "boyes.co.uk"),

            // Garden & pets
            M(1486, "Blue Diamond Garden",    "bluediamond.gg"),
            M(1487, "British Garden Centres", "britishgardencentres.com"),
            M(1488, "Crocus",                 "crocus.co.uk"),
            M(1489, "Gardening Direct",       "gardeningdirect.co.uk"),
            M(1490, "Hillier Garden Centres", "hillier.co.uk"),
            M(1491, "Notcutts",               "notcutts.co.uk"),
            M(1492, "Squire's Garden",        "squiresgardencentres.co.uk"),
            M(1493, "Suttons Seeds",          "suttons.co.uk"),
            M(1494, "Thompson & Morgan",      "thompson-morgan.com"),
            M(1495, "Wyevale",                "wyevalegardencentres.co.uk"),
            M(1496, "Homebase Garden",        "homebase.co.uk"),
            M(1497, "Gardman",                "gardman.co.uk"),
            M(1498, "Pets at Home",           "petsathome.com"),
            M(1499, "Jollyes",                "jollyes.co.uk"),
            M(1500, "Pets Corner",            "petscorner.co.uk"),
            M(1501, "Zooplus",                "zooplus.co.uk"),
            M(1502, "Fetch",                  "fetch.co.uk"),
            M(1503, "Bern Pet Foods",         "bernpetfoods.co.uk"),
            M(1504, "Vets4Pets",              "vets4pets.com"),
            M(1505, "Medivet",                "medivetgroup.com"),
            M(1506, "Companion Care",         "companioncare.co.uk"),
            M(1507, "Blue Cross",             "bluecross.org.uk"),
            M(1508, "PDSA",                   "pdsa.org.uk"),
            M(1509, "Tails.com",              "tails.com"),
            M(1510, "Butternut Box",          "butternutbox.com"),

            // Books, stationery, toys & gifts
            M(1511, "Waterstones",            "waterstones.com"),
            M(1512, "Blackwell's",            "blackwells.co.uk"),
            M(1513, "Foyles",                 "foyles.co.uk"),
            M(1514, "WHSmith",                "whsmith.co.uk"),
            M(1515, "The Works",              "theworks.co.uk"),
            M(1516, "Wordery",                "wordery.com"),
            M(1517, "World of Books",         "wob.com"),
            M(1518, "Book Depository",        "bookdepository.com"),
            M(1519, "Hive",                   "hive.co.uk"),
            M(1520, "Barnes & Noble",         "barnesandnoble.com"),
            M(1521, "Ryman",                  "ryman.co.uk"),
            M(1522, "Paperchase",             "paperchase.com"),
            M(1523, "Cass Art",               "cassart.co.uk"),
            M(1524, "Hobbycraft",             "hobbycraft.co.uk"),
            M(1525, "The Range Crafts",       "therange.co.uk"),
            M(1526, "Staples",                "staples.co.uk"),
            M(1527, "Viking Direct",          "viking-direct.co.uk"),
            M(1528, "Office Outlet",          "officeoutlet.com"),
            M(1529, "Euroffice",              "euroffice.co.uk"),
            M(1530, "The Entertainer",        "thetoyshop.com"),
            M(1531, "Hamleys",                "hamleys.com"),
            M(1532, "Lego Store",             "lego.com"),
            M(1533, "Build-A-Bear",           "buildabear.co.uk"),
            M(1534, "Character.com",          "character.com"),
            M(1535, "Toymaster",              "toymaster.co.uk"),
            M(1536, "Games Workshop",         "games-workshop.com"),
            M(1537, "Warhammer",              "warhammer.com"),
            M(1538, "Card Factory",           "cardfactory.co.uk"),
            M(1539, "Clintons",               "clintonsretail.com"),
            M(1540, "Moonpig",                "moonpig.com"),
            M(1541, "Funky Pigeon",           "funkypigeon.com"),
            M(1542, "Not on the High Street", "notonthehighstreet.com"),
            M(1543, "Etsy",                   "etsy.com"),
            M(1544, "Prezzybox",              "prezzybox.com"),
            M(1545, "Menkind",                "menkind.co.uk"),
            M(1546, "Firebox",                "firebox.com"),
            M(1547, "Interflora",             "interflora.co.uk"),
            M(1548, "Bloom & Wild",           "bloomandwild.com"),
            M(1549, "Serenata Flowers",       "serenataflowers.com"),
            M(1550, "Hotel Chocolat",         "hotelchocolat.com"),

            // Sports & outdoors
            M(1551, "Wiggle",                "wiggle.co.uk"),
            M(1552, "Chain Reaction Cycles", "chainreactioncycles.com"),
            M(1553, "Evans Cycles",          "evanscycles.com"),
            M(1554, "Halfords Cycling",      "halfords.com"),
            M(1555, "Tredz",                 "tredz.co.uk"),
            M(1556, "Rutland Cycling",       "rutlandcycling.com"),
            M(1557, "Cycle Republic",        "cyclerepublic.com"),
            M(1558, "Sigma Sports",          "sigmasports.com"),
            M(1559, "Go Outdoors",           "gooutdoors.co.uk"),
            M(1560, "Millets",               "millets.co.uk"),
            M(1561, "Snow and Rock",         "snowandrock.com"),
            M(1562, "Ellis Brigham",         "ellis-brigham.com"),
            M(1563, "Runners Need",          "runnersneed.com"),
            M(1564, "Sweatshop",             "sweatshop.co.uk"),
            M(1565, "Up and Running",        "upandrunning.co.uk"),
            M(1566, "Wiggle Running",        "wiggle.co.uk"),
            M(1567, "Sweaty Betty",          "sweatybetty.com"),
            M(1568, "Castore",               "castore.com"),
            M(1569, "Lovell Rugby",          "lovell-rugby.co.uk"),
            M(1570, "Rugby Store",           "rugbystore.co.uk"),
            M(1571, "Pro Direct Soccer",     "prodirectsoccer.com"),
            M(1572, "Kitbag",                "kitbag.com"),
            M(1573, "Golf Online",           "golfonline.co.uk"),
            M(1574, "American Golf",         "americangolf.co.uk"),
            M(1575, "Direct Golf",           "directgolf.co.uk"),
            M(1576, "Fishing Republic",      "fishingrepublic.net"),
            M(1577, "Angling Direct",        "anglingdirect.co.uk"),
            M(1578, "Surfdome",              "surfdome.com"),
            M(1579, "Boardriders",           "boardriders.co.uk"),
            M(1580, "Absolute Snow",         "absolute-snow.co.uk"),
            M(1581, "Decathlon Outdoor",     "decathlon.co.uk"),
            M(1582, "Alpkit",                "alpkit.com"),
            M(1583, "Tiso",                  "tiso.com"),
            M(1584, "Nevisport",             "nevisport.com"),
            M(1585, "Simply Hike",           "simplyhike.co.uk"),

            // Jewellery & accessories
            M(1586, "Ernest Jones",           "ernestjones.co.uk"),
            M(1587, "H Samuel",               "hsamuel.co.uk"),
            M(1588, "Beaverbrooks",           "beaverbrooks.co.uk"),
            M(1589, "Goldsmiths",             "goldsmiths.co.uk"),
            M(1590, "Fraser Hart",            "fraserhart.co.uk"),
            M(1591, "Warren James",           "warrenjames.co.uk"),
            M(1592, "Pandora",                "pandora.net"),
            M(1593, "Swarovski",              "swarovski.com"),
            M(1594, "Thomas Sabo",            "thomassabo.com"),
            M(1595, "Links of London",        "linksoflondon.com"),
            M(1596, "Monica Vinader",         "monicavinader.com"),
            M(1597, "Astley Clarke",          "astleyclarke.com"),
            M(1598, "Missoma",                "missoma.com"),
            M(1599, "Accessorize",            "accessorize.com"),
            M(1600, "Claire's",               "claires.com"),
            M(1601, "Watch Shop",             "watchshop.com"),
            M(1602, "Watches of Switzerland", "watches-of-switzerland.co.uk"),
            M(1603, "Tag Heuer",              "tagheuer.com"),
            M(1604, "Rolex",                  "rolex.com"),
            M(1605, "Fossil",                 "fossil.com"),
            M(1606, "Daniel Wellington",      "danielwellington.com"),
            M(1607, "Olivia Burton",          "oliviaburton.com"),
            M(1608, "Michael Kors",           "michaelkors.co.uk"),
            M(1609, "Mulberry",               "mulberry.com"),
            M(1610, "Cath Kidston",           "cathkidston.com"),

            // Banks, insurance & finance
            M(1611, "Barclays",                   "barclays.co.uk"),
            M(1612, "HSBC",                       "hsbc.co.uk"),
            M(1613, "Lloyds Bank",                "lloydsbank.com"),
            M(1614, "NatWest",                    "natwest.com"),
            M(1615, "Santander",                  "santander.co.uk"),
            M(1616, "Halifax",                    "halifax.co.uk"),
            M(1617, "Nationwide",                 "nationwide.co.uk"),
            M(1618, "TSB",                        "tsb.co.uk"),
            M(1619, "Royal Bank of Scotland",     "rbs.co.uk"),
            M(1620, "Bank of Scotland",           "bankofscotland.co.uk"),
            M(1621, "Co-operative Bank",          "co-operativebank.co.uk"),
            M(1622, "Metro Bank",                 "metrobankonline.co.uk"),
            M(1623, "Monzo",                      "monzo.com"),
            M(1624, "Starling Bank",              "starlingbank.com"),
            M(1625, "Revolut",                    "revolut.com"),
            M(1626, "Chase UK",                   "chase.co.uk"),
            M(1627, "First Direct",               "firstdirect.com"),
            M(1628, "Virgin Money",               "virginmoney.com"),
            M(1629, "Yorkshire Building Society", "ybs.co.uk"),
            M(1630, "Skipton Building Society",   "skipton.co.uk"),
            M(1631, "Coventry Building Society",  "coventrybuildingsociety.co.uk"),
            M(1632, "Aviva",                      "aviva.co.uk"),
            M(1633, "Direct Line",                "directline.com"),
            M(1634, "Admiral",                    "admiral.com"),
            M(1635, "Churchill",                  "churchill.com"),
            M(1636, "Hastings Direct",            "hastingsdirect.com"),
            M(1637, "LV",                         "lv.com"),
            M(1638, "More Than",                  "morethan.com"),
            M(1639, "Esure",                      "esure.com"),
            M(1640, "Legal & General",            "legalandgeneral.com"),
            M(1641, "Scottish Widows",            "scottishwidows.co.uk"),
            M(1642, "Zurich",                     "zurich.co.uk"),
            M(1643, "AXA",                        "axa.co.uk"),
            M(1644, "Allianz",                    "allianz.co.uk"),
            M(1645, "Compare the Market",         "comparethemarket.com"),
            M(1646, "MoneySuperMarket",           "moneysupermarket.com"),
            M(1647, "GoCompare",                  "gocompare.com"),
            M(1648, "Confused.com",               "confused.com"),
            M(1649, "Hargreaves Lansdown",        "hl.co.uk"),
            M(1650, "AJ Bell",                    "ajbell.co.uk"),
            M(1651, "Vanguard UK",                "vanguardinvestor.co.uk"),
            M(1652, "Nutmeg",                     "nutmeg.com"),
            M(1653, "Wise",                       "wise.com"),
            M(1654, "American Express",           "americanexpress.com"),
            M(1655, "Capital One",                "capitalone.co.uk"),

            // Telecom, utilities & councils
            M(1656, "Sky Mobile",         "sky.com"),
            M(1657, "Virgin Mobile",      "virginmedia.com"),
            M(1658, "Lebara",             "lebara.co.uk"),
            M(1659, "Lycamobile",         "lycamobile.co.uk"),
            M(1660, "VOXI",               "voxi.co.uk"),
            M(1661, "SMARTY",             "smarty.co.uk"),
            M(1662, "iD Mobile",          "idmobile.co.uk"),
            M(1663, "Shell Energy",       "shellenergy.co.uk"),
            M(1664, "Utility Warehouse",  "utilitywarehouse.co.uk"),
            M(1665, "Bulb",               "bulb.co.uk"),
            M(1666, "So Energy",          "so.energy"),
            M(1667, "Good Energy",        "goodenergy.co.uk"),
            M(1668, "Ecotricity",         "ecotricity.co.uk"),
            M(1669, "Utilita",            "utilita.co.uk"),
            M(1670, "Anglian Water",      "anglianwater.co.uk"),
            M(1671, "Yorkshire Water",    "yorkshirewater.com"),
            M(1672, "United Utilities",   "unitedutilities.com"),
            M(1673, "Southern Water",     "southernwater.co.uk"),
            M(1674, "Wessex Water",       "wessexwater.co.uk"),
            M(1675, "South West Water",   "southwestwater.co.uk"),
            M(1676, "Scottish Water",     "scottishwater.co.uk"),
            M(1677, "Northumbrian Water", "nwl.co.uk"),
            M(1678, "Council Tax",        "gov.uk"),
            M(1679, "HMRC",               "gov.uk"),
            M(1680, "Royal Mail",         "royalmail.com"),

            // Travel, hotels & transport
            M(1681, "Premier Inn",           "premierinn.com"),
            M(1682, "Travelodge",            "travelodge.co.uk"),
            M(1683, "Holiday Inn",           "ihg.com"),
            M(1684, "Hilton",                "hilton.com"),
            M(1685, "Marriott",              "marriott.co.uk"),
            M(1686, "Ibis",                  "accor.com"),
            M(1687, "Novotel",               "accor.com"),
            M(1688, "Mercure",               "accor.com"),
            M(1689, "Radisson Blu",          "radissonhotels.com"),
            M(1690, "Village Hotels",        "village-hotels.co.uk"),
            M(1691, "Malmaison",             "malmaison.com"),
            M(1692, "Hotel du Vin",          "hotelduvin.com"),
            M(1693, "YHA",                   "yha.org.uk"),
            M(1694, "Center Parcs",          "centerparcs.co.uk"),
            M(1695, "Butlins",               "butlins.com"),
            M(1696, "Haven",                 "haven.com"),
            M(1697, "Pontins",               "pontins.com"),
            M(1698, "Booking.com",           "booking.com"),
            M(1699, "Expedia",               "expedia.co.uk"),
            M(1700, "Hotels.com",            "hotels.com"),
            M(1701, "Airbnb",                "airbnb.co.uk"),
            M(1702, "Trivago",               "trivago.co.uk"),
            M(1703, "Skyscanner",            "skyscanner.net"),
            M(1704, "Lastminute.com",        "lastminute.com"),
            M(1705, "On the Beach",          "onthebeach.co.uk"),
            M(1706, "Loveholidays",          "loveholidays.com"),
            M(1707, "Jet2holidays",          "jet2holidays.com"),
            M(1708, "First Choice",          "firstchoice.co.uk"),
            M(1709, "Thomas Cook",           "thomascook.com"),
            M(1710, "Virgin Atlantic",       "virginatlantic.com"),
            M(1711, "Wizz Air",              "wizzair.com"),
            M(1712, "Vueling",               "vueling.com"),
            M(1713, "Aer Lingus",            "aerlingus.com"),
            M(1714, "KLM",                   "klm.co.uk"),
            M(1715, "Emirates",              "emirates.com"),
            M(1716, "P&O Ferries",           "poferries.com"),
            M(1717, "DFDS",                  "dfds.co.uk"),
            M(1718, "Brittany Ferries",      "brittanyferries.co.uk"),
            M(1719, "Stena Line",            "stenaline.co.uk"),
            M(1720, "LeShuttle",             "leshuttle.com"),
            M(1721, "Enterprise Rent-A-Car", "enterprise.co.uk"),
            M(1722, "Hertz",                 "hertz.co.uk"),
            M(1723, "Avis",                  "avis.co.uk"),
            M(1724, "Europcar",              "europcar.co.uk"),
            M(1725, "Sixt",                  "sixt.co.uk"),
            M(1726, "Zipcar",                "zipcar.co.uk"),
            M(1727, "NCP Parking",           "ncp.co.uk"),
            M(1728, "RingGo",                "ringgo.co.uk"),
            M(1729, "JustPark",              "justpark.com"),
            M(1730, "APCOA Parking",         "apcoa.co.uk"),

            // Entertainment, gyms & leisure
            M(1731, "Odeon",                  "odeon.co.uk"),
            M(1732, "Cineworld",              "cineworld.co.uk"),
            M(1733, "Vue Cinemas",            "myvue.com"),
            M(1734, "Everyman Cinema",        "everymancinema.com"),
            M(1735, "Picturehouse",           "picturehouses.com"),
            M(1736, "Showcase Cinemas",       "showcasecinemas.co.uk"),
            M(1737, "Curzon",                 "curzon.com"),
            M(1738, "Ticketmaster",           "ticketmaster.co.uk"),
            M(1739, "See Tickets",            "seetickets.com"),
            M(1740, "ATG Tickets",            "atgtickets.com"),
            M(1741, "Eventbrite",             "eventbrite.co.uk"),
            M(1742, "Merlin Entertainments",  "merlinentertainments.biz"),
            M(1743, "Alton Towers",           "altontowers.com"),
            M(1744, "Thorpe Park",            "thorpepark.com"),
            M(1745, "Legoland Windsor",       "legoland.co.uk"),
            M(1746, "Chessington",            "chessington.com"),
            M(1747, "Madame Tussauds",        "madametussauds.com"),
            M(1748, "London Eye",             "londoneye.com"),
            M(1749, "Sea Life",               "visitsealife.com"),
            M(1750, "National Trust",         "nationaltrust.org.uk"),
            M(1751, "English Heritage",       "english-heritage.org.uk"),
            M(1752, "Historic Royal Palaces", "hrp.org.uk"),
            M(1753, "ZSL London Zoo",         "zsl.org"),
            M(1754, "Hollywood Bowl",         "hollywoodbowl.co.uk"),
            M(1755, "Tenpin",                 "tenpin.co.uk"),
            M(1756, "Nuffield Health Gym",    "nuffieldhealth.com"),
            M(1757, "Anytime Fitness",        "anytimefitness.co.uk"),
            M(1758, "Fitness First",          "fitnessfirst.co.uk"),
            M(1759, "Bannatyne",              "bannatyne.co.uk"),
            M(1760, "Better Leisure",         "better.org.uk"),

            // Online marketplaces & services
            M(1761, "Vinted",               "vinted.co.uk"),
            M(1762, "Depop",                "depop.com"),
            M(1763, "Gumtree",              "gumtree.com"),
            M(1764, "Facebook Marketplace", "facebook.com"),
            M(1765, "OnBuy",                "onbuy.com"),
            M(1766, "Wish",                 "wish.com"),
            M(1767, "AliExpress",           "aliexpress.com"),
            M(1768, "Temu",                 "temu.com"),
            M(1769, "Groupon",              "groupon.co.uk"),
            M(1770, "Wowcher",              "wowcher.co.uk"),
            M(1771, "Trustpilot",           "trustpilot.com"),
            M(1772, "Just Park Services",   "justpark.com"),
            M(1773, "Checkatrade",          "checkatrade.com"),
            M(1774, "Rated People",         "ratedpeople.com"),
            M(1775, "MyBuilder",            "mybuilder.com"),
            M(1776, "TaskRabbit",           "taskrabbit.co.uk"),
            M(1777, "Fiverr",               "fiverr.com"),
            M(1778, "Upwork",               "upwork.com"),
            M(1779, "Etsy UK",              "etsy.com"),
            M(1780, "Redbubble",            "redbubble.com"),
            M(1781, "Vistaprint",           "vistaprint.co.uk"),
            M(1782, "Moo",                  "moo.com"),
            M(1783, "Snappy Snaps",         "snappysnaps.co.uk"),
            M(1784, "Photobox",             "photobox.co.uk"),
            M(1785, "Shutterstock",         "shutterstock.com"),
            M(1786, "Canva",                "canva.com"),
            M(1787, "Squarespace",          "squarespace.com"),
            M(1788, "Wix",                  "wix.com"),
            M(1789, "GoDaddy",              "godaddy.com"),
            M(1790, "123 Reg",              "123-reg.co.uk"),
            M(1791, "Ionos",                "ionos.co.uk"),
            M(1792, "OVH",                  "ovhcloud.com"),
            M(1793, "Hetzner",              "hetzner.com"),
            M(1794, "DigitalOcean",         "digitalocean.com"),
            M(1795, "Linode",               "linode.com"),
            M(1796, "Evri",                 "evri.com"),
            M(1797, "DPD",                  "dpd.co.uk"),
            M(1798, "Yodel",                "yodel.co.uk"),
            M(1799, "ParcelForce",          "parcelforce.com"),
            M(1800, "UPS",                  "ups.com"),
        };

        /// <summary>
        /// Alternative spellings receipts and card statements print. Written in readable form and
        /// normalized on the way in, so "Tesco Stores Limited" is stored as "tescostoreslimited".
        /// Ids are positional — append only, never reorder.
        /// </summary>
        private static readonly (int MerchantId, string Alias)[] RawAliases =
        {
            (1, "Tesco Stores"), (1, "Tesco Stores Limited"), (1, "Tesco Express"), (1, "Tesco Extra"),
            (1, "Tesco Metro"), (1, "Tesco Superstore"), (1, "Tesco Petrol Station"),
            (2, "Sainsbury"), (2, "Sainsburys Local"), (2, "J Sainsbury plc"), (2, "Sainsburys Superstore"),
            (3, "Asda Stores"), (3, "Asda Superstore"), (3, "Asda Living"),
            (4, "Morrisons Daily"), (4, "Wm Morrisons"),
            (5, "Aldi Stores"),
            (6, "Lidl GB"), (6, "Lidl UK"),
            (7, "Co-op Food"), (7, "The Co-operative Food"), (7, "Cooperative Food"),
            (8, "Waitrose & Partners"),
            (9, "M&S"), (9, "Marks and Spencer"), (9, "M&S Simply Food"), (9, "M&S Foodhall"),
            (10, "Iceland Foods"),
            (24, "Holland and Barrett"),
            (26, "Shell UK"), (26, "Shell UK Oil"), (26, "Shell Service Station"),
            (27, "BP Connect"), (27, "BP Fuel"), (27, "BP Petrol"),
            (28, "Esso Express"), (28, "Esso Petrol Station"),
            (34, "Halfords Autocentre"),
            (35, "Kwik Fit Plus"),
            (41, "Costa"), (41, "Costa Express"), (41, "Costa Limited"),
            (42, "Starbucks Coffee"),
            (43, "Nero Caffe"),
            (44, "Pret"),
            (45, "Greggs plc"), (45, "Greggs The Bakers"),
            (46, "McDs"), (46, "Macdonalds"),
            (47, "Burger King UK"),
            (48, "Kentucky Fried Chicken"),
            (50, "Nandos Chickenland"),
            (53, "Dominos Pizza"),
            (54, "Pizza Hut Delivery"),
            (55, "Papa Johns Pizza"),
            (56, "Five Guys Burgers and Fries"),
            (71, "JD Wetherspoon"), (71, "Wetherspoons"),
            (74, "Just Eat Takeaway"),
            (75, "Uber Eats UK"),
            (76, "TfL"), (76, "TfL Travel Charge"), (76, "TfL Rail"), (76, "Oyster Card"),
            (77, "The Trainline"), (77, "Trainline com"),
            (81, "Great Western Railway"),
            (87, "Uber BV"), (87, "Uber Trip"), (87, "Uber UK"),
            (90, "National Express Ltd"),
            (95, "easyJet Airline"),
            (101, "Amazon UK"), (101, "Amazon co uk"), (101, "Amazon Marketplace"), (101, "AMZN Mktplace"), (101, "Amazon Digital"),
            (102, "eBay UK"),
            (103, "Argos Ltd"), (103, "Argos Retail"),
            (104, "John Lewis & Partners"), (104, "John Lewis Partnership"),
            (111, "TK Maxx UK"),
            (113, "JD Sport"),
            (125, "Currys PC World"), (125, "PC World"), (125, "Currys Digital"),
            (127, "Apple Store"), (127, "Apple UK"),
            (131, "B and Q"), (131, "B&Q Ltd"),
            (132, "Screwfix Direct"),
            (133, "Wickes Building Supplies"),
            (138, "IKEA Ltd"), (138, "IKEA UK"),
            (142, "TJ Morris"),
            (143, "B&M Bargains"), (143, "B&M Stores"),
            (153, "Lloyds Pharmacy Ltd"),
            (163, "PureGym Limited"),
            (166, "BT Group"), (166, "BT Broadband"),
            (167, "EE Limited"), (167, "EE Mobile"),
            (168, "Vodafone UK"), (168, "Vodafone Ltd"),
            (169, "O2 UK"), (169, "Telefonica O2"),
            (170, "Three UK"), (170, "Hutchison 3G"),
            (171, "Sky UK"), (171, "Sky Digital"), (171, "Sky Subscription"),
            (172, "Virgin Media UK"),
            (177, "British Gas Trading"), (177, "British Gas Energy"),
            (178, "EDF"), (178, "EDF Energy UK"),
            (179, "E.ON Next"),
            (180, "Octopus Energy Ltd"),
            (181, "OVO Energy Ltd"),
            (182, "Scottish Power Energy"),
            (184, "Thames Water Utilities"),
            (185, "Severn Trent Water"),
            (186, "Netflix com"), (186, "Netflix UK"),
            (187, "Spotify UK"), (187, "Spotify AB"),
            (188, "Disney Plus"), (188, "Disney+ UK"),
            (189, "Prime Video"), (189, "Amazon Prime"),
            (190, "NOW TV"),
            (191, "iTunes"),
            (192, "YouTube Premium"), (192, "Google YouTube"),
            (193, "Audible UK"),
            (194, "Adobe Systems"), (194, "Adobe Creative Cloud"),
            (195, "Microsoft Corporation"), (195, "MSFT"),
            (196, "Google Payment"), (196, "Google Ireland"), (196, "Google Play"),
            (198, "PayPal UK"), (198, "PayPal Inst"),
            (200, "TV Licence"),

            // Sub-brands of the merchants above — kept as aliases so a receipt for
            // "Tesco Petrol" or "Zizzi Express" rolls up to the parent merchant.
            (5, "Aldi Local"),
            (6, "Lidl Plus"),
            (7, "Local Co-op"),
            (18, "Londis Express"),
            (16, "Spar Express"),
            (19, "Premier Express"),
            (17, "Cost Cutter Express"),
            (15, "Nisa Local"),
            (4, "Morrisons Market Kitchen"),
            (109, "Selfridges Food Hall"),
            (3, "Asda Petrol"),
            (4, "Morrisons Petrol"),
            (2, "Sainsburys Petrol"),
            (1, "Tesco Petrol"),
            (20, "Costco Petrol"),
            (26, "Shell Recharge"),
            (35, "Kwik Fit Mobile"),
            (43, "Caffe Nero Express"),
            (43, "Nero Express"),
            (63, "Zizzi Express"),
            (61, "Yo Sushi Express"),
            (60, "Wasabi Sushi"),
            (64, "Ask Italian Express"),
            (41, "Costa Express Drive Thru"),
            (132, "Screwfix Trade"),
            (135, "Toolstation Trade"),
            (131, "TradePoint B&Q"),
            (141, "Wilko Home"),
        };

        public static readonly object[] Aliases = RawAliases
            .Select((a, index) => (object)new
            {
                Id = index + 1,
                MerchantId = a.MerchantId,
                NormalizedAlias = Merchant.Normalize(a.Alias)
            })
            .ToArray();
    }
}
