name: self-host-deploy
on:
  push:
    branches: [self-host]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker compose --env-file /opt/expensetracker/.env up -d --build
      - run: docker image prune -f